export * from './about/about.component';
export * from './contact/contact.component';
export * from './home/home.component';
export * from './auth/login/login.component';
export * from './auth/register/register.component';
export * from './checkout/checkout.component';
export * from './shop/shop.component';
export * from './profile/profile.component';
export * from '.';
